name: Build Android

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm32"]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          sudo apt update
          sudo apt install -y bison flex ninja-build python3-mako python3-yaml zlib1g-dev
          python3 -m pip install --break-system-packages meson
          export ANDROID_NDK_ROOT="${ANDROID_NDK_ROOT:-$ANDROID_NDK_LATEST_HOME}"
          envsubst <android-${{matrix.arch}} >build-crossfile
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/mesa.git
          cd mesa
          git apply --reject --whitespace=fix ../mesa-zink.diff || echo "git apply failed"
          meson setup "build-android" \
            --prefix=/tmp/zink \
            --cross-file "../build-crossfile" \
            -Dplatforms=android \
            -Dplatform-sdk-version=25 \
            -Dandroid-stub=true \
            -Dllvm=disabled \
            -Dxlib-lease=disabled \
            -Degl=disabled \
            -Dgbm=disabled \
            -Dglx=disabled \
            -Dopengl=true \
            -Dosmesa=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=zink \
            -Dandroid-libbacktrace=disabled \
            -Dbuildtype=release
          ninja -C "build-android" install

      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: libzink_${{matrix.arch}}
          path: /tmp/zink
