name: Pure Direct Build ANGLE

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: "Direct Compile ARM32"
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - name: Install Tools and Android NDK
        run: |
          sudo apt update
          # Устанавливаем официальный компилятор generate-ninja (gn) прямо из репозиторией Ubuntu
          sudo apt install -y git python3 curl ninja-build generate-ninja

      - name: Clone ANGLE Directly from GitHub
        run: |
          git clone --depth 1 https://github.com angle-src
          cd angle-src
          
          # Скачиваем три критические Vulkan-зависимости, без которых GN не создаст конфиг
          git clone --depth 1 https://googlesource.com third_party/vulkan-deps
          git clone --depth 1 https://googlesource.com third_party/glslang
          git clone --depth 1 https://googlesource.com third_party/spirv-tools

      - name: Generate GN Config
        run: |
          cd angle-src
          
          # Указываем путь к Android NDK, который уже встроен в систему GitHub Actions по умолчанию
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          
          # Запускаем системный компилятор gn
          gn gen out/Android --args="
            target_os=\"android\"
            target_cpu=\"arm\"
            is_debug=false
            dcheck_always_on=false
            angle_build_all=false
            angle_enable_vulkan=true
            angle_enable_gl=false
            is_component_build=false
            symbol_level=0
            android_ndk_root=\"$ANDROID_NDK_HOME\"
          "

      - name: Compile
        run: |
          cd angle-src
          ninja -C out/Android -j $(nproc) libEGL libGLESv2

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: angle_arm32_fixed
          path: |
            angle-src/out/Android/lib.unstripped/libEGL.so
            angle-src/out/Android/lib.unstripped/libGLESv2.so
